In [1]:
import numpy as np


In [2]:
INPUT = np.asmatrix([6.15840302,-2.86995972])
TARGET = np.asmatrix([5.56039031])


## define the Signoid function and its derivative

In [14]:

def sigmoid(z, prime=False):
    if prime:
        f = sigmoid(z, prime=False)
        return np.multiply(f , ( 1.0 - f ) )

    return 1.0/(1.0 + np.exp(-1.0 * z))





# set up weights

The network is built as follows:
1. Input layer - 2 neurons
2. 1st hidden layer - 4 neurons
3. 2nd hidden layer - 2 neurons
4. Output layer - 1 neurons

there for we have 3 weights matrices:
- W1 - between input and 1st hidden.
- W2 - between 1st hidden and 2nd hidden.
- W3 - between 2nd hidden and output layer.

The wieght matrix is in size : (input nodes + 1 for bias ) X (amount of neurons in current layer)

In [29]:
# shape (3, 4)  - 2 input node + 1 bias to 4 neurons in 1st hidden layer
W1 = np.asmatrix([[0.51639863,0.57066759,0.02847423,0.17152166],
[0.68527698,0.83389686,0.30696622,0.89361308],
[0.72154386,0.18993895,0.55422759,0.35213195]])

# shape (5, 3)  - 4 input node + 1 bias to 3 neurons in 2nd hidden layer
W2 = np.asmatrix([[0.1818924,0.78560176,0.96548322],
[0.23235366,0.08356143,0.60354842],
[0.72899276,0.27623883,0.68530633],
[0.51786747,0.04848454,0.13786924],
[0.18696743,0.9943179,0.5206654]])

# shape (4, 1)  - 3 input node + 1 bias to 1neurons in output layer
W3 = np.asmatrix([[0.57878954],
[0.73481906],
[0.54196177],
[0.91315356]])


# Feed Forward


In [30]:
layers_output = []

In [31]:
#first - pad a bias to the input data
values_rows = INPUT.shape[0]
bias_and_values = np.concatenate(  [np.ones((values_rows, 1)) , INPUT ], axis=1)
bias_and_values

matrix([[ 1.        ,  6.15840302, -2.86995972]])

In [32]:
# calculate pre activation
hidden_layer_1_pre_activation = np.dot(bias_and_values, W1)
hidden_layer_1_pre_activation

matrix([[ 2.66580864,  5.1610234 ,  0.32828507,  4.66414664]])

In [33]:
# calculate post activation
hidden_layer_1_post_activation = sigmoid( hidden_layer_1_pre_activation )
layers_output.append(hidden_layer_1_post_activation)
hidden_layer_1_post_activation

matrix([[ 0.93497869,  0.99429689,  0.58134205,  0.99066075]])

In [34]:
values_rows = hidden_layer_1_post_activation.shape[0]
bias_and_values = np.concatenate(  [np.ones((values_rows, 1)) , hidden_layer_1_post_activation ], axis=1)
bias_and_values

matrix([[ 1.        ,  0.93497869,  0.99429689,  0.58134205,  0.99066075]])

In [35]:
# calculate pre activation
hidden_layer_2_pre_activation = np.dot(bias_and_values, W2)
hidden_layer_2_pre_activation
# calculate post activation
hidden_layer_2_post_activation = sigmoid( hidden_layer_2_pre_activation )
layers_output.append(hidden_layer_2_post_activation)
hidden_layer_2_post_activation

matrix([[ 0.83344648,  0.89581924,  0.94306033]])

In [36]:
values_rows = hidden_layer_2_post_activation.shape[0]
bias_and_values = np.concatenate(  [np.ones((values_rows, 1)) , hidden_layer_2_post_activation ], axis=1)
bias_and_values

matrix([[ 1.        ,  0.83344648,  0.89581924,  0.94306033]])

In [37]:
# calculate pre activation
output_layer_pre_activation = np.dot(bias_and_values, W3)

# calculate post activation
output_layer_post_activation = sigmoid( output_layer_pre_activation )
layers_output.append(output_layer_post_activation)
output_layer_post_activation

matrix([[ 0.92675509]])

# Back Propogation

We've got the feed forward results of the 

In [38]:
layers_output

[matrix([[ 0.93497869,  0.99429689,  0.58134205,  0.99066075]]),
 matrix([[ 0.83344648,  0.89581924,  0.94306033]]),
 matrix([[ 0.92675509]])]

In [41]:
layers_delta = []


In [45]:
# from https://sudeepraja.github.io/Neural/

values_rows = hidden_layer_2_post_activation.shape[0]
hidden_layer_2_post_activation_with_bias = np.concatenate(  [np.ones((values_rows, 1)) , hidden_layer_2_post_activation ], axis=1)
delta_out =  np.multiply ( output_layer_post_activation - TARGET, sigmoid( np.dot( W3, hidden_layer_2_post_activation_with_bias)  , prime=True))

layers_delta.append(delta_out)
delta_out

matrix([[-1.06656323, -1.09354832, -1.08391422, -1.07623676],
        [-1.01510249, -1.05623298, -1.04145654, -1.02975454],
        [-1.07734337, -1.10127413, -1.09274146, -1.08593303],
        [-0.94691021, -1.00562372, -0.98434797, -0.96764429]])